[package]
name = "jumping_frog_problem"
version = "0.3.0"
edition = "2021"
authors = ["Lex_Xeno"]

[dependencies]
cliclack = "0.3"
crossterm = "0.28.1"
indoc = "2.0"
log = "0.4"
pretty_env_logger = "0.5"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
