[package]
name = "jumping_frog_problem"
version = "1.0.0"
edition = "2021"
authors = ["Lex_Xeno"]

[dependencies]
anyhow = "1.0.89"
cliclack = "0.3"
getset = "0.1.3"
indoc = "2.0"
log = "0.4"
pretty_env_logger = "0.5"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
