[package]
name = "jumping_frog_problem"
version = "0.1.0"
edition = "2021"
authors = ["Lex_Xeno"]

[dependencies]
cliclack = "0.3.2"
indoc = "2.0.5"
log = "0.4.22"
pretty_env_logger = "0.5.0"
rand = "0.8.5"
serde = { version = "1.0.206", features = ["derive"] }
toml = "0.8.19"
